version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: fastapi_db
    restart: always
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: fastapi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: fastapi_app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://fastapi_user:securepassword@db/fastapi_db
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    container_name: fastapi_nginx
    restart: always
    ports:
      - "80:
